
select AWARD_ID,SEQUENCE_NUMBER,AWARD_NUMBER,DOCUMENT_NUMBER,AWARD_SEQUENCE_STATUS,UPDATE_USER from AWARD where AWARD_ID in (select max(AWARD_ID) from AWARD where AWARD_NUMBER in (select distinct AWARD_NUMBER from AWARD) group by AWARD_NUMBER);

select AWARD_ID,SEQUENCE_NUMBER,AWARD_NUMBER,DOCUMENT_NUMBER,AWARD_SEQUENCE_STATUS,UPDATE_USER from AWARD where AWARD_ID in (select max(AWARD_ID) from AWARD where AWARD_SEQUENCE_STATUS='ACTIVE' and AWARD_NUMBER in (select distinct AWARD_NUMBER from AWARD) group by AWARD_NUMBER);

